{
  try {
    next();
  } catch (e) {
    onError(e);
  }
}
