{
  done(new Error("done was called with error"));
}
